### ISSUE TITLE
Filename can either be an absolute HTTP[s] URL, *or* a file name

### ISSUE THREAD

**Issue by gaetandezeiraud** [reiniiriarios/electron-forge-publisher-local#1]
Can be amazing if we can set the http prefix. And the package automatically add it in the RELEASES file.
Because otherwise, there is an error `Filename can either be an absolute HTTP[s] URL, *or* a file name`. 

Don't work:
`0FE5A7C264F23846413C4E9121C2FD0572A67C19 0.0.2/dezeiraud_play-0.0.2-full.nupkg 86496683`

Work:
`0FE5A7C264F23846413C4E9121C2FD0572A67C19 http://download.dezeiraud.test/update/0.0.2/dezeiraud_play-0.0.2-full.nupkg 86496683`

**Comment by reiniiriarios** [comment]
Updated!
